name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        username: _json_key
        password: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
        registry: gcr.io

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-project:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-project:${{ github.sha }}
        
